### ISSUE TITLE
Revise Sidebar

### ISSUE THREAD

**Issue by chrisw310** [COMP3000-2018/cstr-client#1]
Replace "charts" with:
1. Physical Examination - (link to current charts page)
2. Investigations

Replace "app" with:
1. GCS - "../gcs"
2. ANZBA Guidelines - link to "https://anzba.org.au/care/referral-criteria/"
3. Burn Surface Area - "../burn"

New entries at the bottom of the sidebar named:
1. "discussion starters"
2. "case story"

**Comment by rexsw** [comment]
I've changed around the buttons and added the discussion starters, However I couldn't figure out how to make the story and discussion starters bottom align so If someone could take a look that'd be great

**Comment by chrisw310** [comment]
I'll take a look

**Comment by chrisw310** [comment]
Done. I was going to do category headers, but putting the story stuff at the bottom cleaned it up enough
