### ISSUE TITLE
Style charts to match design

### ISSUE THREAD

**Issue by chrisw310** [COMP3000-2018/cstr-client#6]
Ask chris if he's asked you to do it

**Comment by chrisw310** [comment]
@rexsw I'll do layout (e.g. the cards), and you style charts?

**Comment by rexsw** [comment]
Sure sounds good

**Comment by chrisw310** [comment]
I made a simple accordion menu for now, good enough to present but I'll look at a dashboard view later

**Comment by chrisw310** [comment]
Decided against dashboard view. Closing
